### ISSUE TITLE
Change all GitHub URLs to be lowercase 

### ISSUE THREAD

**Issue by AmnestyAM** [aspirepress/documentation#34]
Some URLs are have uppercase names, this was changed in the [/index.md file](https://github.com/aspirepress/documentation/blob/main/docs/index.md) in [this pull request](https://github.com/aspirepress/documentation/pull/33), for consistency I recombed we do the same for all other URLs too. 

@ipajen feel free to pick this one up if you want, otherwise I will next week. thanks for the PR.

**Comment by ipajen** [comment]
Should it be changed? 

https://github.com/aspirepress/AspireSync and https://github.com/aspirepress/AspireSync is not using all lowercase on there github repo but https://github.com/aspirepress/aspireupdate did change to lowercase. @AmnestyAM  I let you pick it up. Thanks!
