### ISSUE TITLE
Feature Request Improve ay11 accessibility

### ISSUE THREAD

**Issue by ipajen** [aspirepress/documentation#39]
When checking on the free tool: (https://wave.webaim.org/report#/https://docs.aspirepress.org) there is issues that would great if fixed.

Language missing or invalid
Missing alternative text
Missing form label
Empty link
Very low contrast

**Comment by asirota** [comment]
Run the tool and submit what needs to be fixed 🙏

**Comment by ipajen** [comment]
![wave](https://github.com/user-attachments/assets/62d2c269-171c-40df-b64e-55db43db0342)

Language missing or invalid
The language of the document is not identified or a lang attribute value is invalid.

Missing form label
A form control does not have a corresponding label.

Missing alternative text
Image alternative text is not present.

Very low contrast (1.76:1)
Very low contrast between text and background colors.
