### ISSUE TITLE
Diagram for AspireUpdate is wrong

### ISSUE THREAD

**Issue by sarah-savage** [aspirepress/documentation#4]
The [diagram for AspireUpdate](https://docs.aspirepress.org/aspireupdate/) assumes that we will treat the .org repository as canonical and pull anything we don't know from there.

This is wrong.

Once we begin to implement our own endpoints, we will treat unknown plugins the same way WP .org does: we simply won't indicate if they should be updated or not. While AspireSync will continue to provide data on the .org repository for a bit our goal is to eliminate that as a point of failure or a point of difficulty for us moving forward.

If you can update the docs to reflect that this is not in fact the protocol, that would be helpful.

**Comment by asirota** [comment]
So to confirm we will diagram the to be state. We won't ever delegate plugin or theme updates to worg even in the initial released version. Is that correct?
