### ISSUE TITLE
Obsoleted information about AspireUpdate

### ISSUE THREAD

**Issue by ipajen** [aspirepress/documentation#5]
On https://docs.aspirepress.org/aspireupdate/

### Design of Phase 1 of AspirePress
The plugin rewrites all API calls to api.aspirepress.org or to another AspireCloud powered API

**should be updated to api.aspirecloud.org endpoint**

### Configuration
You can turn on the debug log and reset the settings. Use the advanced=true query param in the settings screen to turn on advanced configuration settings.

**To my knowledge the advanced=true query parameter has been removed.**

**Comment by ipajen** [comment]
[WP Playground Blueprint](https://github.com/aspirepress/AspireUpdate/blob/playground-ready/assets/playground/blueprint.json)
givs 404

**Comment by asirota** [comment]
updated diagram

**Comment by asirota** [comment]
fixed
